/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.olympus.system.hawkdeskpos.frontend.stock;

import com.olympus.system.hawkdeskpos.db.dao.Brands;
import com.olympus.system.hawkdeskpos.db.dao.Category;
import com.olympus.system.hawkdeskpos.db.dao.Item;
import com.olympus.system.hawkdeskpos.db.util.Controller;
import com.olympus.system.hawkdeskpos.frontend.Home;
import com.olympus.system.hawkdeskpos.frontend.model.Brand;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.java.balloontip.BalloonTip;
import net.java.balloontip.styles.RoundedBalloonStyle;
import net.java.balloontip.utils.TimingUtils;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author Thusitha
 */
public class AddNewItem extends javax.swing.JInternalFrame {

    SessionFactory sf = null;
    Session ses = null;
    String stat = " ";

    public AddNewItem() {
        super("Item Details", false, true, false);
        initComponents();
        btnUpdate.setVisible(false);
        sf = Controller.getSessionFactory();
        ses = sf.openSession();
        getCatList();
        getBrandList();

    }

    public AddNewItem(Item itm) {
        this();
        jLabel1.setText("Update Item");
        stat = "update";
        btnSave.setVisible(false);
        btnUpdate.setVisible(true);
        Item item = itm;
        txtItemName.setText(item.getItemName());
        cmbBoxCat.setSelectedItem(item.getCategory().getCategoryName());
        cmbBoxBrand.setSelectedItem(item.getBrands().getBrandName());
        spinnerLevel.setValue(item.getMinLevel());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            private Image image;{
                try{
                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/back2.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }
            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(), getHeight(), this);
            }
        };
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        cmbBoxCat = new javax.swing.JComboBox();
        cmbBoxBrand = new javax.swing.JComboBox();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        spinnerLevel = new javax.swing.JSpinner();
        btnUpdate = new javax.swing.JButton();

        setTitle("Add New Item");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stock/itemAdd icon.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(540, 470));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stock/itemAdd big.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setText("Add new Item");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Medicine Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Category");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Brand");

        txtItemName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtItemName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtItemNameFocusLost(evt);
            }
        });
        txtItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtItemNameKeyTyped(evt);
            }
        });

        cmbBoxCat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbBoxCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Select Item Category --" }));
        cmbBoxCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxCatActionPerformed(evt);
            }
        });

        cmbBoxBrand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbBoxBrand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Select Item Brand --" }));
        cmbBoxBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxBrandActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Minimum Level");

        spinnerLevel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinnerLevel.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(5), Integer.valueOf(1), null, Integer.valueOf(1)));
        spinnerLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spinnerLevelKeyTyped(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnUpdate.setText("Save");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbBoxCat, 0, 217, Short.MAX_VALUE)
                            .addComponent(cmbBoxBrand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtItemName)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spinnerLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbBoxCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbBoxBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinnerLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        int i = JOptionPane.showConfirmDialog(this, "Are you sure?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            this.dispose();
        }
        System.gc();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtItemNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyTyped


    }//GEN-LAST:event_txtItemNameKeyTyped

    private void spinnerLevelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spinnerLevelKeyTyped

        System.out.println(evt.getKeyChar());
    }//GEN-LAST:event_spinnerLevelKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (txtItemName.getText().equals("")) {
            txtItemName.grabFocus();
            BalloonTip tip = new BalloonTip(txtItemName, "<html><font color='white'>Please fill this field</font></html>", style, false);
            tip.setVisible(true);
            TimingUtils.showTimedBalloon(tip, 2000);

        } else if (cmbBoxCat.getSelectedIndex() == 0) {
            BalloonTip tip = new BalloonTip(cmbBoxCat, "<html><font color='white'>Please select a category</font></html>", style, false);
            tip.setVisible(true);
            TimingUtils.showTimedBalloon(tip, 2000);

        } else if (cmbBoxBrand.getSelectedIndex() == 0) {
            BalloonTip tip = new BalloonTip(cmbBoxBrand, "<html><font color='white'>Please select a brand</font></html>", style, false);
            tip.setVisible(true);
            TimingUtils.showTimedBalloon(tip, 2000);

        } else {
            Item item = new Item();
            Criteria c = ses.createCriteria(Category.class);
            c.add(Restrictions.eq("categoryName", cmbBoxCat.getSelectedItem().toString()));

            Category cat = (Category) c.uniqueResult();
            Criteria c2 = ses.createCriteria(Brands.class);
            c2.add(Restrictions.eq("brandName", cmbBoxBrand.getSelectedItem().toString()));

            Brands brand = (Brands) c2.uniqueResult();
            Transaction trans = ses.beginTransaction();

            item.setItemName(txtItemName.getText());
            item.setBrands(brand);
            item.setCategory(cat);
            item.setMinLevel(Integer.parseInt(spinnerLevel.getValue().toString()));
            item.setStat("active");

            ses.save(item);
            trans.commit();

            int i = JOptionPane.showConfirmDialog(this, "Item saved. \n Do you want to add another item?");
            clear();
            try {
                AddStock.setItems();
                AddStock.cmbBoxItmName.setSelectedIndex(AddStock.cmbBoxItmName.getItemCount());
            } catch (Exception e) {
                System.out.println("error");
            }
            if (i == 1) {
                this.dispose();
            }
        }
        Home.setNotifications();
        System.gc();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void clear() {
        txtItemName.setText("");
        cmbBoxBrand.setSelectedIndex(0);
        cmbBoxCat.setSelectedIndex(0);
        spinnerLevel.setValue(0);
    }

    private void cmbBoxCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxCatActionPerformed

        if (cmbBoxCat.getSelectedIndex() == 1) {
            new com.olympus.system.hawkdeskpos.frontend.model.Category().addCategory();
            getCatList();
            cmbBoxCat.setSelectedIndex(cmbBoxCat.getItemCount() - 1);
            System.gc();
        }
    }//GEN-LAST:event_cmbBoxCatActionPerformed

    private void cmbBoxBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxBrandActionPerformed

        if (cmbBoxBrand.getSelectedIndex() == 1) {
            new Brand().addBrand();
            getBrandList();
            cmbBoxBrand.setSelectedIndex(cmbBoxBrand.getItemCount() - 1);
        }

    }//GEN-LAST:event_cmbBoxBrandActionPerformed

    RoundedBalloonStyle style = new RoundedBalloonStyle(10, 8, Color.black, Color.black);
    private void txtItemNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemNameFocusLost

        if (!stat.equals("update")) {
            if (txtItemName.getText().equals("")) {
                txtItemName.grabFocus();
                BalloonTip tip = new BalloonTip(txtItemName, "<html><font color='white'>Please fill this field</font></html>", style, false);
                tip.setVisible(true);
                TimingUtils.showTimedBalloon(tip, 2000);

            } else {
                try {
                    Criteria cr = ses.createCriteria(Item.class);
                    cr.add(Restrictions.eq("itemName", txtItemName.getText()));
                    cr.add(Restrictions.eq("stat", "active"));
                    List lst = cr.list();
                    if (!lst.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Entered medecine already in the stock.\n Please enter another name");
                    }
                } catch (Exception e) {

                }
            }
        }

        System.gc();
    }//GEN-LAST:event_txtItemNameFocusLost

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        Criteria cr = ses.createCriteria(Item.class);
        cr.add(Restrictions.eq("itemName", txtItemName.getText()));
        Item item = (Item) cr.uniqueResult();

        Transaction tr = ses.beginTransaction();

        item.setBrands((Brands) ses.createCriteria(Brands.class).add(Restrictions.eq("brandName", cmbBoxBrand.getSelectedItem().toString())).uniqueResult());
        item.setCategory((Category) ses.createCriteria(Category.class).add(Restrictions.eq("categoryName", cmbBoxCat.getSelectedItem().toString())).uniqueResult());
        item.setMinLevel(Integer.parseInt(spinnerLevel.getValue().toString()));
        item.setStat("active");

        ses.saveOrUpdate(item);
        tr.commit();

//        JOptionPane.showMessageDialog(this, "Item updated");
        try {
            ViewItems items = new ViewItems();
            Home.HomeDeskpane.add(items);
            items.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
        }
        this.dispose();

        System.gc();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing

        Home.setNotifications();
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtItemNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemNameFocusGained

    }//GEN-LAST:event_txtItemNameFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbBoxBrand;
    private javax.swing.JComboBox cmbBoxCat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner spinnerLevel;
    private javax.swing.JTextField txtItemName;
    // End of variables declaration//GEN-END:variables

    private void getCatList() {
        Vector v = new Vector();
        v.add("-- Select category --");
        v.add("Add new category");
        Criteria cr = ses.createCriteria(Category.class);
        ArrayList<Category> ls = (ArrayList<Category>) cr.list();
        for (int i = 0; i < ls.size(); i++) {
            Category category = ls.get(i);
            v.add(category.getCategoryName());

        }
        cmbBoxCat.setModel(new DefaultComboBoxModel(v));
        System.gc();

    }

    private void getBrandList() {
        Vector v = new Vector();
        v.add("-- Select Brand --");
        v.add("Add new brand");
        Criteria cr = ses.createCriteria(Brands.class);
        ArrayList<Brands> lst = (ArrayList<Brands>) cr.list();
        for (int i = 0; i < lst.size(); i++) {
            Brands brands = lst.get(i);
            v.add(brands.getBrandName());
        }
        cmbBoxBrand.setModel(new DefaultComboBoxModel(v));
        System.gc();

    }
}
