/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.olympus.system.hawkdeskpos.frontend.stock;

import com.olympus.system.hawkdeskpos.db.dao.Grn;
import com.olympus.system.hawkdeskpos.db.dao.Grninfo;
import com.olympus.system.hawkdeskpos.db.dao.Item;
import com.olympus.system.hawkdeskpos.db.dao.Stock;
import com.olympus.system.hawkdeskpos.db.util.Controller;
import com.olympus.system.hawkdeskpos.frontend.Home;
import java.util.Date;
import java.util.Vector;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SessionFactory;
import net.java.balloontip.BalloonTip;
import org.hibernate.Transaction;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.HibernateException;
import org.hibernate.criterion.Projections;
import org.hibernate.criterion.Restrictions;
import net.java.balloontip.utils.TimingUtils;
import net.java.balloontip.styles.RoundedBalloonStyle;

/**
 *
 * @author Thusitha
 */
public class AddStock extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddStock
     */
    SessionFactory sf = null;
    static Session ses = null;
    DefaultTableModel dtm = null;
    int products = 0;
    int qty = 0;
    double tot = 0.0;

    public AddStock() {
        super("Add new Stock", true, true, true, false);
        initComponents();
        sf = Controller.getSessionFactory();
        ses = sf.openSession();
        dtm = (DefaultTableModel) jTable1.getModel();
//        jPanel1.setBackground(new Color(255, 255, 255, 0));
        setItems();
    }

    public AddStock(Item itm) {
        this();
        jFormattedTextField1.setValue(itm.getItemId());
        cmbBoxItmName.setSelectedItem(itm.getItemName());

    }

    public static void setItems() {
        Criteria cr = ses.createCriteria(Item.class);
        cr.add(Restrictions.eq("stat", "active"));
        ArrayList<Item> lst = (ArrayList<Item>) cr.list();
        Vector v = new Vector();
        v.add("-- Select item --");
        v.add("Add new item");
        for (int i = 0; i < lst.size(); i++) {
            Item item = lst.get(i);
            v.add(item.getItemName());

        }
        cmbBoxItmName.setModel(new DefaultComboBoxModel(v));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        pnlBack = new javax.swing.JPanel(){

            private Image image;{
                try{
                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/back2.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }
            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(), getHeight(), this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel(){

            private Image image;{
                try{
                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/back2.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }
            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(), getHeight(), this);
            }
        };
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBatch = new javax.swing.JTextField();
        spinnerQty = new javax.swing.JSpinner();
        formatItemCost = new javax.swing.JFormattedTextField();
        formatSellPrice = new javax.swing.JFormattedTextField();
        btnClear = new javax.swing.JButton();
        btnAddtoTable = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        dateExpire = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        cmbBoxItmName = new javax.swing.JComboBox();
        txtCat = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel(){

            private Image image;{
                try{
                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/back.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }
            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(), getHeight(), this);
            }
        };
        jLabel9 = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblTot = new javax.swing.JLabel();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Inventory-maintenance-add.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add New Stock");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#ID", "Item Name", "Item Category", "Item Brand", "Expire Date", "Quantity", "Cost", "Item Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(50);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(2).setMinWidth(100);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(3).setMinWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(4).setMinWidth(100);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(5).setMinWidth(50);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(6).setMinWidth(70);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(70);
            jTable1.getColumnModel().getColumn(7).setMinWidth(100);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Category");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Brand");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Batch");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Quantity");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Item Cost");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Item Selling Price");

        txtBatch.setEditable(false);
        txtBatch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        spinnerQty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinnerQty.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        spinnerQty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spinnerQtyMouseClicked(evt);
            }
        });
        spinnerQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spinnerQtyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                spinnerQtyFocusLost(evt);
            }
        });

        formatItemCost.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        formatItemCost.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        formatItemCost.setText("0.00");
        formatItemCost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        formatItemCost.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                formatItemCostCaretUpdate(evt);
            }
        });
        formatItemCost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formatItemCostFocusGained(evt);
            }
        });
        formatItemCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formatItemCostKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formatItemCostKeyTyped(evt);
            }
        });

        formatSellPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        formatSellPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        formatSellPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        formatSellPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formatSellPriceKeyPressed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnAddtoTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddtoTable.setText("Add");
        btnAddtoTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoTableActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Expire Date");

        dateExpire.setDateFormatString("yyyy-MM-dd");
        dateExpire.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateExpirePropertyChange(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Item Name");

        cmbBoxItmName.setEditable(true);
        cmbBoxItmName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbBoxItmName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Type to Search item --" }));
        cmbBoxItmName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxItmNameActionPerformed(evt);
            }
        });

        txtCat.setEditable(false);
        txtCat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtBrand.setEditable(false);
        txtBrand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Item Id");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        jFormattedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddtoTable, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBatch)
                            .addComponent(formatItemCost)
                            .addComponent(formatSellPrice)
                            .addComponent(txtBrand)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinnerQty, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateExpire, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(86, 86, 86)
                        .addComponent(jFormattedTextField1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(63, 63, 63)
                        .addComponent(cmbBoxItmName, 0, 184, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(73, 73, 73)
                        .addComponent(txtCat)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbBoxItmName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateExpire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(formatItemCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(formatSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddtoTable, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Products");

        lblProduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblProduct.setText("0");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Quantity");

        lblQty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQty.setText("0");

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Total");

        lblTot.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTot.setText("0.00");
        lblTot.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(lblQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(253, 253, 253)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(lblTot, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblProduct))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblQty))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblTot))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlBackLayout = new javax.swing.GroupLayout(pnlBack);
        pnlBack.setLayout(pnlBackLayout);
        pnlBackLayout.setHorizontalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackLayout.setVerticalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setViewportView(pnlBack);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formatSellPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formatSellPriceKeyPressed

        if (Character.isLetter(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_formatSellPriceKeyPressed

    private void formatItemCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formatItemCostKeyTyped

    }//GEN-LAST:event_formatItemCostKeyTyped

    private void formatItemCostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formatItemCostKeyReleased

        if (Character.isLetter(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_formatItemCostKeyReleased


    private void btnAddtoTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoTableActionPerformed

        if (cmbBoxItmName.getSelectedIndex() == 0 && cmbBoxItmName.getSelectedIndex() == 1) {
            BalloonTip tip = new BalloonTip(cmbBoxItmName, "<html><font color='white'>Please select valid item.</font></html>", style, false);
            tip.setVisible(true);
            TimingUtils.showTimedBalloon(tip, 3000);

        } else if (formatItemCost.getValue() == null) {
            BalloonTip tip = new BalloonTip(formatItemCost, "<html><font color='white'>Please enter the item cost</font></html>", style, false);
            tip.setVisible(true);
            TimingUtils.showTimedBalloon(tip, 3000);

        } else if (formatSellPrice.getValue() == null) {
            BalloonTip tip = new BalloonTip(formatSellPrice, "<html><font color='white'>Please enter the item sellin price</font></html>", style, false);
            tip.setVisible(true);
            TimingUtils.showTimedBalloon(tip, 3000);

        } else {
            String itm = "false";
            int r = jTable1.getRowCount();
            int c = jTable1.getColumnCount();

            int sr = 0;
            int sc = 0;
            for (int i = 0; i < r; i++) {
                for (int j = 0; j < c; j++) {
                    if (Integer.parseInt(jTable1.getValueAt(i, 0).toString()) == itmId) {
                        itm = "true";
                        sr = i;
                        sc = j;
                        break;
                    } else {
                        itm = "false";
                    }
                }
            }

            if (itm.equals("false")) {
                Vector v = new Vector();
                v.add(itmId);
                v.add(cmbBoxItmName.getSelectedItem());
                v.add(txtCat.getText());
                v.add(txtBrand.getText());
                v.add(new SimpleDateFormat("yyyy-MM-dd").format(dateExpire.getDate()));
                v.add(spinnerQty.getValue());
                v.add(Double.parseDouble(formatItemCost.getValue().toString()));
                v.add(Double.parseDouble(formatSellPrice.getValue().toString()));
                dtm.addRow(v);
                setFooter();

            } else {
                int i = JOptionPane.showConfirmDialog(this, cmbBoxItmName.getSelectedItem() + " is already in the list. \n Do you want to "
                        + "adjust the quantity?", "Confirm", JOptionPane.YES_NO_OPTION);
                if (i == 0) {
                    String j = JOptionPane.showInputDialog(this, "Please enter new quantity");
                    jTable1.setValueAt(j, sr, 5);
                    setFooter();

                }
            }
        }
        clear();
        System.gc();
    }//GEN-LAST:event_btnAddtoTableActionPerformed

    int itmId = 0;
    private void cmbBoxItmNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxItmNameActionPerformed

        if (cmbBoxItmName.getSelectedIndex() == 0) {
            clear();
        }
        if (cmbBoxItmName.getSelectedIndex() == 1) {
            AddNewItem item = new AddNewItem();
            Home.HomeDeskpane.add(item);
            item.setVisible(true);

        } else {
            Criteria c = ses.createCriteria(Item.class);
            c.add(Restrictions.eq("itemName", cmbBoxItmName.getSelectedItem().toString()));
            Item itm = (Item) c.uniqueResult();
            try {
                itmId = itm.getItemId();
                txtCat.setText(itm.getCategory().getCategoryName());
                txtBrand.setText(itm.getBrands().getBrandName());
//            int i = itm.getItemId();

                Criteria c2 = ses.createCriteria(Stock.class);
                c2.add(Restrictions.eq("item", itm));
                c2.setProjection(Projections.count("batch"));
                long l = (long) c2.uniqueResult();
                txtBatch.setText(String.valueOf(l + 1));

            } catch (Exception e) {
                System.out.println("error");
            }
        }

    }//GEN-LAST:event_cmbBoxItmNameActionPerformed

    public void refreshItemList() {
        new Thread(
                new Runnable() {
                    @Override
                    public void run() {
                        try {
                            setItems();
                            Thread.sleep(5000);
                            System.out.println("running");
                        } catch (Exception e) {
                        }
                    }
                }
        ).start();
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (jTable1.getRowCount() != 0) {
            Transaction tr = ses.beginTransaction();
            Grninfo info = new Grninfo();
            info.setDate(new Date(System.currentTimeMillis()));
            info.setSubTotal(tot);
            ses.save(info);
            tr.commit();

            saveGrn();
            System.gc();
            Home.setNotifications();
        } else {
            JOptionPane.showMessageDialog(this, "Please add items for save to stock.");
        }

    }

    public void saveGrn() throws NumberFormatException, HibernateException {
        int r = jTable1.getRowCount();
        int c = jTable1.getColumnCount();
        SessionFactory sf1 = Controller.getSessionFactory();
        Session ses2 = sf1.openSession();

        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        String a[] = new String[10];
        for (int i = 0; i < r; i++) {
            Criteria gi = ses.createCriteria(Grninfo.class);
            gi.setProjection(Projections.max("grnNo"));
            int id = (int) gi.uniqueResult();

            Grn grn = new Grn();
            Transaction trns = ses.beginTransaction();
            grn.setGrninfo((Grninfo) ses.load(Grninfo.class, id));

            Stock stock = new Stock();
            Transaction stk = ses2.beginTransaction();

            for (int j = 0; j < c; j++) {

                if (j == 0) {
//                    setting up grn values
                    a[i] = String.valueOf(dt.getValueAt(i, 0));
                    Criteria cr = ses.createCriteria(Item.class);
                    cr.add(Restrictions.eq("itemId", Integer.parseInt(a[i])));
                    Item itm = (Item) cr.uniqueResult();
                    grn.setItem(itm);

//                    setting up stock values
                    stock.setItem(itm);
                    stock.setGrninfo((Grninfo) ses.load(Grninfo.class, id));
                    Criteria bt = ses2.createCriteria(Stock.class);
                    bt.add(Restrictions.eq("item", itm));
                    bt.setProjection(Projections.count("batch"));
                    long bno = (long) bt.uniqueResult();
                    stock.setBatch(String.valueOf(bno + 1));

                } else if (j == 4) {
                    try {
                        a[i] = String.valueOf(dt.getValueAt(i, 4));
                        System.out.println(a[i]);
                        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                        Date d = dateFormat.parse(a[i]);
                        Long l = d.getTime();
                        grn.setExpireDate(new Date(l));

                        stock.setExpireDate(new Date(l));
                    } catch (ParseException ex) {
                        Logger.getLogger(AddStock.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else if (j == 5) {
                    a[i] = String.valueOf(dt.getValueAt(i, 5));
                    grn.setItemQty(Integer.parseInt(a[i]));

                    stock.setQty(Integer.parseInt(a[i]));

                } else if (j == 6) {
                    a[i] = String.valueOf(dt.getValueAt(i, 6));
                    grn.setItemCost(Double.parseDouble(a[i]));

                    stock.setCost(Double.parseDouble(a[i]));

                } else if (j == 7) {
                    a[i] = String.valueOf(dt.getValueAt(i, 7));
                    grn.setItemPrice(Double.parseDouble(a[i]));

                    stock.setPrice(Double.parseDouble(a[i]));
                    stock.setStat("available");

                    System.out.println("Saving...");
                    ses.save(grn);
                    ses2.save(stock);

                }

            }
            trns.commit();
            stk.commit();
            System.out.println("Saved..");

            jTable1.setModel(dtm);
            lblProduct.setText("0");
            lblQty.setText("0");
            lblTot.setText("0.00");
        }
        JOptionPane.showMessageDialog(this, "Record Saved Successfully");

        int rr = jTable1.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        for (int j = 0; j < rr; j++) {
            dtm.removeRow(0);
        }

        System.gc();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

        int k = jTable1.getRowCount();
        if (k != 0) {
            if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
                int i = JOptionPane.showConfirmDialog(this, "Do you want to delete this record.", "Confirm", JOptionPane.YES_NO_OPTION);
                if (i == 0) {
                    System.out.println(tot);
                    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                    int j = jTable1.getSelectedRow();
                    int q = Integer.parseInt(String.valueOf(jTable1.getValueAt(j, 5)));
                    double c = Double.parseDouble(String.valueOf(jTable1.getValueAt(j, 6)));
                    qty -= q;
                    products -= 1;
                    tot -= (c * q);
                    lblProduct.setText(String.valueOf(products));
                    lblQty.setText(String.valueOf(qty));
                    lblTot.setText(String.valueOf(tot));
                    dtm.removeRow(j);
                    jTable1.setModel(dtm);
                    jTable1.changeSelection(j, jTable1.getSelectedColumn(), false, false);
                    System.out.println(tot);
                }
            }
//            setFooter();
        }
        System.gc();
    }//GEN-LAST:event_jTable1KeyPressed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }

    public void clear() {
        cmbBoxItmName.setSelectedIndex(0);
        txtBatch.setText(" ");
        txtBrand.setText(" ");
        txtCat.setText(" ");
        formatItemCost.setText("0.00");
        formatSellPrice.setText("0.00");
    }//GEN-LAST:event_btnClearActionPerformed

    RoundedBalloonStyle style = new RoundedBalloonStyle(10, 8, Color.BLACK, Color.BLACK);
    private void spinnerQtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spinnerQtyFocusGained


    }//GEN-LAST:event_spinnerQtyFocusGained

    private void dateExpirePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateExpirePropertyChange

        if (dateExpire.getDate() != null) {
            Date today = new Date(System.currentTimeMillis());
            Date exDay = dateExpire.getDate();
            int i = exDay.compareTo(today);
            if (i < 0) {
                BalloonTip tip = new BalloonTip(dateExpire, "<html><font color='white'>Expire date must be greater than today</font></html>", style, false);
                tip.setVisible(true);
                TimingUtils.showTimedBalloon(tip, 2000);
                dateExpire.grabFocus();
            }
        }

    }//GEN-LAST:event_dateExpirePropertyChange

    private void spinnerQtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spinnerQtyFocusLost

        System.out.println("Spinner focus lost");
    }//GEN-LAST:event_spinnerQtyFocusLost

    private void spinnerQtyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spinnerQtyMouseClicked

        if (dateExpire.getDate() == null) {
            BalloonTip tip = new BalloonTip(dateExpire, "<html><font color='white'>Expire date cannto be empty</font></html>", style, false);
            tip.setVisible(true);
            TimingUtils.showTimedBalloon(tip, 2000);
            dateExpire.grabFocus();
        }
    }//GEN-LAST:event_spinnerQtyMouseClicked

    private void formatItemCostCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_formatItemCostCaretUpdate


    }//GEN-LAST:event_formatItemCostCaretUpdate

    private void formatItemCostFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatItemCostFocusGained

        formatItemCost.selectAll();
    }//GEN-LAST:event_formatItemCostFocusGained

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed


    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField1KeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                Item itm = (Item) ses.load(Item.class, Integer.parseInt(jFormattedTextField1.getValue().toString()));
                if (!itm.getStat().equals("active")) {
                    JOptionPane.showMessageDialog(this, "This item currently remove from stock");
                    jFormattedTextField1.setText("");
                    jFormattedTextField1.grabFocus();
                } else {
                    cmbBoxItmName.setSelectedItem(itm.getItemName());
                    dateExpire.grabFocus();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Cannot find item.");
            }
        }
    }//GEN-LAST:event_jFormattedTextField1KeyReleased

    public void setFooter() {
        int r = jTable1.getRowCount();
        qty = 0;
        products = 0;
        tot = 0;
        for (int i = 0; i < r; i++) {
            qty += Integer.parseInt(jTable1.getValueAt(i, 5).toString());
            products = jTable1.getRowCount();
            tot += Double.parseDouble(jTable1.getValueAt(i, 6).toString()) * Integer.parseInt(jTable1.getValueAt(i, 5).toString());

            lblProduct.setText(String.valueOf(products));
            lblQty.setText(String.valueOf(qty));
            lblTot.setText(String.valueOf(tot));

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtoTable;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    public static javax.swing.JComboBox cmbBoxItmName;
    private com.toedter.calendar.JDateChooser dateExpire;
    private javax.swing.JFormattedTextField formatItemCost;
    private javax.swing.JFormattedTextField formatSellPrice;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblTot;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JSpinner spinnerQty;
    private javax.swing.JTextField txtBatch;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCat;
    // End of variables declaration//GEN-END:variables
}
