/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.olympus.system.hawkdeskpos.frontend;

import com.olympus.system.hawkdeskpos.util.Configs;
import java.awt.Frame;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Thusitha
 */
public class DbBackup extends javax.swing.JInternalFrame {

    /**
     * Creates new form DbBackup
     */
    Configs con = new Configs();

    public DbBackup() {
        super("Backup Database", false, true, false, false);
        initComponents();
        jFileChooser1.setApproveButtonText("Save");

//        pnlBackup.setVisible(true);
        String option = con.getProp("BackupOption");

        cmbboxPlanOption.setSelectedItem(con.getProp("AutoBackupRule"));
        cmbboxTime.setSelectedItem(con.getProp("AutoBackupTime"));
        cmbboxTime.setSelectedItem((con.getProp("AutoBackupLocation")));
        txtautoBackupLoc.setText(con.getProp("AutoBackupLocation"));

        txtbackupLocation.setText(con.getProp("ManualLocation"));

        if (option.equals("Auto")) {
            radioAuto.setSelected(true);
            radioAutoActionPerformed(null);
        } else if (option.equals("Manual")) {
            radioManual.setSelected(true);
            radioManualActionPerformed(null);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        pnlBackup = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        radioAuto = new javax.swing.JRadioButton();
        radioManual = new javax.swing.JRadioButton();
        pnlManualBackup = new javax.swing.JPanel();
        txtbackupLocation = new javax.swing.JTextField();
        btnLocation = new javax.swing.JButton();
        btnBackupNow = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmbboxPlanOption = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtautoBackupLoc = new javax.swing.JTextField();
        btnAutoBackupLocation = new javax.swing.JButton();
        cmbboxTime = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Database Backup Settings");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Option"));

        radioAuto.setText("Automatic Backup ");
        radioAuto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioAutoStateChanged(evt);
            }
        });
        radioAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAutoActionPerformed(evt);
            }
        });
        radioAuto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                radioAutoPropertyChange(evt);
            }
        });

        radioManual.setText("Manual Backup");
        radioManual.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioManualStateChanged(evt);
            }
        });
        radioManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioManualActionPerformed(evt);
            }
        });
        radioManual.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                radioManualPropertyChange(evt);
            }
        });

        btnLocation.setText("Change");
        btnLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocationActionPerformed(evt);
            }
        });

        btnBackupNow.setText("Backup Now");
        btnBackupNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupNowActionPerformed(evt);
            }
        });

        jLabel5.setText("Location");

        javax.swing.GroupLayout pnlManualBackupLayout = new javax.swing.GroupLayout(pnlManualBackup);
        pnlManualBackup.setLayout(pnlManualBackupLayout);
        pnlManualBackupLayout.setHorizontalGroup(
            pnlManualBackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManualBackupLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlManualBackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(btnBackupNow)
                    .addGroup(pnlManualBackupLayout.createSequentialGroup()
                        .addComponent(txtbackupLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLocation)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlManualBackupLayout.setVerticalGroup(
            pnlManualBackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManualBackupLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addGroup(pnlManualBackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbackupLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocation))
                .addGap(18, 18, 18)
                .addComponent(btnBackupNow)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        cmbboxPlanOption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Everyday", "Friday", "Sunday", "Month End" }));

        jLabel2.setText("at");

        jLabel3.setText("Backup Plan");

        jLabel4.setText("Location");

        txtautoBackupLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtautoBackupLocActionPerformed(evt);
            }
        });

        btnAutoBackupLocation.setText("Change");
        btnAutoBackupLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoBackupLocationActionPerformed(evt);
            }
        });

        cmbboxTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "09:00:00 AM", "10:00:00 AM", "11:00:00 AM", "12:00:00 AM", "01:00:00 PM", "02:00:00 PM", "03:00:00 PM", "04:00:00 PM", "05:00:00 PM", "06:00:00 PM" }));
        cmbboxTime.setSelectedItem("05:00:00 PM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cmbboxPlanOption, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbboxTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtautoBackupLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAutoBackupLocation)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbboxPlanOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbboxTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtautoBackupLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAutoBackupLocation))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlManualBackup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radioManual, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioAuto, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(radioAuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioManual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlManualBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBackupLayout = new javax.swing.GroupLayout(pnlBackup);
        pnlBackup.setLayout(pnlBackupLayout);
        pnlBackupLayout.setHorizontalGroup(
            pnlBackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlBackupLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlBackupLayout.setVerticalGroup(
            pnlBackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioAutoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioAutoStateChanged

    }//GEN-LAST:event_radioAutoStateChanged

    private void radioAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAutoActionPerformed

        con.SaveProp("BackupOption", "Auto");
        if (radioAuto.isSelected()) {
            cmbboxPlanOption.setEnabled(true);
            btnAutoBackupLocation.setEnabled(true);
            txtautoBackupLoc.setEnabled(true);
            cmbboxTime.setEnabled(true);

            btnLocation.setEnabled(false);
            txtbackupLocation.setEnabled(false);
            btnBackupNow.setEnabled(false);
        }
    }//GEN-LAST:event_radioAutoActionPerformed

    private void radioAutoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_radioAutoPropertyChange

    }//GEN-LAST:event_radioAutoPropertyChange

    private void radioManualStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioManualStateChanged

    }//GEN-LAST:event_radioManualStateChanged

    private void radioManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioManualActionPerformed

        con.SaveProp("BackupOption", "Manual");
        if (radioManual.isSelected()) {
            btnLocation.setEnabled(true);
            txtbackupLocation.setEnabled(true);
            btnBackupNow.setEnabled(true);

            cmbboxPlanOption.setEnabled(false);
            btnAutoBackupLocation.setEnabled(false);
            txtautoBackupLoc.setEnabled(false);
            cmbboxTime.setEnabled(false);
        }
    }//GEN-LAST:event_radioManualActionPerformed

    private void radioManualPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_radioManualPropertyChange

    }//GEN-LAST:event_radioManualPropertyChange

    private void btnLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocationActionPerformed

        jFileChooser1.setDialogTitle("Select Location");
        jFileChooser1.setCurrentDirectory(new File(con.getProp("ManualLocation")));
        Frame window = new Frame();
        window.setIconImage(new ImageIcon("src/images/finance/track-26_2.png").getImage());
        int i = jFileChooser1.showSaveDialog(window);
        if (i == jFileChooser1.APPROVE_OPTION) {
            File f = jFileChooser1.getSelectedFile();
            txtbackupLocation.setText(f.toString());
            System.out.println(f.toString());
        }
    }//GEN-LAST:event_btnLocationActionPerformed

    private void btnBackupNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupNowActionPerformed

        String sql1 = "C:\\Program Files\\MySQL\\MySQL Server 5.5\\bin\\mysqldump -uroot -p1234 Pharmacy -r" + txtbackupLocation.getText() + ".sql";
        System.out.println(txtbackupLocation.getText());
        try {
            Runtime.getRuntime().exec(sql1);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBackupNowActionPerformed

    private void txtautoBackupLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtautoBackupLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtautoBackupLocActionPerformed

    private void btnAutoBackupLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoBackupLocationActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(con.getProp("AutoBackupLocation")));
        chooser.setDialogTitle("Select Auto Backup Location");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        Frame window = new Frame();
//        window.setIconImage(new ImageIcon("src/images/finance/track-26_2.png").getImage());

        if (chooser.showOpenDialog(window) == JFileChooser.APPROVE_OPTION) {
            System.out.println("getCurrentDirectory(): " + chooser.getCurrentDirectory());
            System.out.println("getSelectedFile() : " + chooser.getSelectedFile());
            txtautoBackupLoc.setText(chooser.getSelectedFile().toString() + "\\");
        } else {
            System.out.println("No Selection ");
        }

    }//GEN-LAST:event_btnAutoBackupLocationActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (radioAuto.isSelected()) {
            con.SaveProp("BackupOption", "Auto");
            con.SaveProp("AutoBackupRule", (String) cmbboxPlanOption.getSelectedItem());
            con.SaveProp("AutoBackupTime", (String) cmbboxTime.getSelectedItem());
            con.SaveProp("AutoBackupLocation", txtautoBackupLoc.getText());
        } else if (radioManual.isSelected()) {
            con.SaveProp("BackupOption", "Manual");
            con.SaveProp("ManualLocation", txtbackupLocation.getText());

        }
        JOptionPane.showMessageDialog(this, "Backup setting saved");
        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutoBackupLocation;
    private javax.swing.JButton btnBackupNow;
    private javax.swing.JButton btnLocation;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbboxPlanOption;
    private javax.swing.JComboBox cmbboxTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlBackup;
    private javax.swing.JPanel pnlManualBackup;
    private javax.swing.JRadioButton radioAuto;
    private javax.swing.JRadioButton radioManual;
    private javax.swing.JTextField txtautoBackupLoc;
    private javax.swing.JTextField txtbackupLocation;
    // End of variables declaration//GEN-END:variables
}
