/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.olympus.system.hawkdeskpos.frontend.sale;

import java.awt.Image;
import java.awt.Color;
import com.olympus.system.hawkdeskpos.db.dao.Invoiceinfo;
import com.olympus.system.hawkdeskpos.db.dao.Item;
import com.olympus.system.hawkdeskpos.db.dao.Stock;
import com.olympus.system.hawkdeskpos.db.util.Controller;
import com.olympus.system.hawkdeskpos.frontend.Conn;
import com.olympus.system.hawkdeskpos.frontend.Home;
import com.olympus.system.hawkdeskpos.frontend.stock.AddStock;
import java.awt.Graphics;
import java.sql.Connection;
import java.awt.event.KeyEvent;
import java.awt.HeadlessException;
import java.beans.PropertyVetoException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.java.balloontip.BalloonTip;
import net.java.balloontip.styles.RoundedBalloonStyle;
import net.java.balloontip.utils.TimingUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.persister.collection.mutation.RowMutationOperations.Restrictions;

/**
 *
 * @author Thusitha
 */
public class Invoice extends javax.swing.JInternalFrame {

    /**
     * Creates new form Invoice
     */
    private static final SessionFactory sf = Controller.getSessionFactory();

    double tot = 0;
    int qty = 0;
    int product = 0;
    double pay = 0.0;
    double dis = 0.0;

    public Invoice() {
        super("Invoice", true, true, true);
        initComponents();
        setTableValues();
    }

    public void setTableValues() {
        try (Session session = sf.openSession()) {

            List<Item> items = session.createQuery(
                    "FROM Item i WHERE i.stat = :stat",
                    Item.class)
                    .setParameter("stat", "active")
                    .getResultList();

            Vector<String> v = new Vector<>();
            v.add("-- Select Item --");
            for (Item item : items) {
                v.add(item.getItemName());
            }
            cmbBoxSearch.setModel(new DefaultComboBoxModel<>(v));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed to load items");
            e.printStackTrace();
        }

        System.gc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel(){

            private Image image;{
                try{
                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/back.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }
            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(), getHeight(), this);
            }
        };
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbBoxSearch = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cmbBoxBatch = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel(){

            private Image image;{
                try{
                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/back2.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }
            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(), getHeight(), this);
            }
        };
        btnUpdateQty = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel(){

            private Image image;{
                try{
                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/back.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }
            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(), getHeight(), this);
            }
        };
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnSavePrint = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPayment = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Invoice");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/sale.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Invoice");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Search Item");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Qty");

        cmbBoxSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbBoxSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Type to find items" }));
        cmbBoxSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxSearchActionPerformed(evt);
            }
        });

        jSpinner1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSpinner1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpinner1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSpinner1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinner1KeyTyped(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Select batch");

        cmbBoxBatch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbBoxBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxBatchActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setText("Type item id");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbBoxSearch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(cmbBoxBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbBoxSearch)
                            .addComponent(jTextField1)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(cmbBoxBatch)))
                .addGap(13, 13, 13))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnUpdateQty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUpdateQty.setText("Update Quantity");
        btnUpdateQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateQtyActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Remove Item");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateQty, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUpdateQty, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item #", "Item Name", "batch", "Item Price", "Qty", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(60);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(2).setMinWidth(100);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(3).setMinWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(4).setMinWidth(50);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(5).setMinWidth(100);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );

        jPanel5.setBackground(java.awt.SystemColor.window);

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnSavePrint.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSavePrint.setText("Save & Print");
        btnSavePrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePrintActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sub Total");

        lblSubTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubTotal.setText("0.00");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Discount");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtDiscount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtDiscount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDiscount.setText("0.00");
        txtDiscount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscountKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Total");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("0.00");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Balance");

        lblBalance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBalance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBalance.setText("0.00");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Payment");

        txtPayment.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtPayment.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPayment.setText("0.00");
        txtPayment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaymentKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(txtPayment))
                        .addGap(130, 130, 130)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnSavePrint, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblSubTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lblTotal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblBalance)
                    .addComponent(jLabel8)
                    .addComponent(txtPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSavePrint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner1KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try (Session session = sf.openSession()) {

                // Find item by name
                Item itm = session.createQuery(
                        "FROM Item i WHERE i.itemName = :name",
                        Item.class)
                        .setParameter("name", cmbBoxSearch.getSelectedItem().toString())
                        .uniqueResult();

                if (itm == null) {
                    JOptionPane.showMessageDialog(this, "Item not found");
                    return;
                }

                // Find stock by item + batch
                Stock stk = session.createQuery(
                        "FROM Stock s WHERE s.item = :item AND s.batch = :batch",
                        Stock.class)
                        .setParameter("item", itm)
                        .setParameter("batch", cmbBoxBatch.getSelectedItem().toString())
                        .uniqueResult();

                if (stk == null) {
                    JOptionPane.showMessageDialog(this, "No stock found for selected batch");
                    return;
                }

                int requested = Integer.parseInt(jSpinner1.getValue().toString());
                if (stk.getQty() < requested) {
                    JOptionPane.showMessageDialog(this,
                            itm.getItemName() + " does not have enough stock for the selected batch.\n"
                            + "Please select another batch.\n"
                            + "Max available: " + stk.getQty());
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid quantity value");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jSpinner1KeyPressed

    private void jSpinner1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner1KeyTyped


    }//GEN-LAST:event_jSpinner1KeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try (Session session = sf.openSession()) {

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

            // Find item by name
            Item itm = session.createQuery(
                    "FROM Item i WHERE i.itemName = :name",
                    Item.class)
                    .setParameter("name", cmbBoxSearch.getSelectedItem().toString())
                    .uniqueResult();

            if (itm == null) {
                throw new NullPointerException("Item not found");
            }

            // Find stock by item + batch
            Stock st = session.createQuery(
                    "FROM Stock s WHERE s.item = :item AND s.batch = :batch",
                    Stock.class)
                    .setParameter("item", itm)
                    .setParameter("batch", cmbBoxBatch.getSelectedItem().toString())
                    .uniqueResult();

            if (st == null) {
                throw new NullPointerException("Stock not found");
            }

            int requestedQty = Integer.parseInt(jSpinner1.getValue().toString());
            int rowCount = jTable1.getRowCount();
            int existingQty = 0;
            boolean itemAlreadyInTable = false;
            int existingRow = -1;

            // Check if the same item+batch combo already exists in the table
            for (int i = 0; i < rowCount; i++) {
                boolean sameItem = jTable1.getValueAt(i, 1).equals(cmbBoxSearch.getSelectedItem());
                boolean sameBatch = jTable1.getValueAt(i, 2).equals(cmbBoxBatch.getSelectedItem());
                if (sameItem && sameBatch) {
                    existingQty += Integer.parseInt(jTable1.getValueAt(i, 4).toString());
                    itemAlreadyInTable = true;
                    existingRow = i;
                }
            }

            NumberFormat f = NumberFormat.getInstance();
            f.setMinimumFractionDigits(2);

            if (itemAlreadyInTable) {
                // Item is already in the table — update quantity in existing row
                if (existingQty + requestedQty > st.getQty()) {
                    JOptionPane.showMessageDialog(this,
                            itm.getItemName() + " does not have enough stock for the selected batch.\n"
                            + "Please select another batch.\n"
                            + "Max available: " + st.getQty());
                } else {
                    int updatedQty = Integer.parseInt(jTable1.getValueAt(existingRow, 4).toString()) + requestedQty;
                    jTable1.setValueAt(updatedQty, existingRow, 4);
                    jTable1.setValueAt(f.format(st.getPrice() * updatedQty), existingRow, 5);
                }

            } else if (st.getQty() >= requestedQty) {
                // New row — item not yet in the table
                Vector<Object> v = new Vector<>();
                v.add(itm.getItemId());
                v.add(itm.getItemName());
                v.add(st.getBatch());
                v.add(f.format(st.getPrice()));
                v.add(requestedQty);
                v.add(f.format(st.getPrice() * requestedQty));
                dtm.addRow(v);
                jTable1.setModel(dtm);

            } else {
                // Requested qty exceeds available stock
                JOptionPane.showMessageDialog(this,
                        itm.getItemName() + " does not have enough stock for the selected batch.\n"
                        + "Please select another batch.\n"
                        + "Max available: " + st.getQty());
                jSpinner1.setValue(st.getQty());
            }

            setFooter();
            System.gc();

        } catch (NullPointerException e) {
            RoundedBalloonStyle style = new RoundedBalloonStyle(10, 8, Color.BLACK, Color.BLACK);
            BalloonTip tip = new BalloonTip(cmbBoxSearch,
                    "<html><font color='white'>Please select an item</font></html>", style, false);
            tip.setVisible(true);
            TimingUtils.showTimedBalloon(tip, 2000);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid quantity value");
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmbBoxSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxSearchActionPerformed

        if (cmbBoxSearch.getSelectedIndex() != 0) {
            try (Session session = sf.openSession()) {

                // Find item by name
                Item itm = session.createQuery(
                        "FROM Item i WHERE i.itemName = :name",
                        Item.class)
                        .setParameter("name", cmbBoxSearch.getSelectedItem().toString())
                        .uniqueResult();

                if (itm == null) {
                    JOptionPane.showMessageDialog(this, "Item not found");
                    return;
                }

                // Find available stock for this item
                List<Stock> lst = session.createQuery(
                        "FROM Stock s WHERE s.item = :item AND s.stat = :stat",
                        Stock.class)
                        .setParameter("item", itm)
                        .setParameter("stat", "available")
                        .getResultList();

                if (lst.isEmpty()) {
                    int choice = JOptionPane.showConfirmDialog(this,
                            "This item is not currently in stock. Do you want to add stock?",
                            "Add New Stock",
                            JOptionPane.YES_NO_OPTION);

                    if (choice == JOptionPane.YES_OPTION) {
                        // Use already-loaded itm instead of a redundant session.load()
                        AddStock addStk = new AddStock(itm);
                        Home.HomeDeskpane.add(addStk);
                        addStk.setVisible(true);
                        try {
                            addStk.setMaximum(true);
                        } catch (PropertyVetoException ex) {
                            Logger.getLogger(Invoice.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                } else {
                    // Populate batch combo box with available batches
                    Vector<String> v = new Vector<>();
                    for (Stock stock : lst) {
                        v.add(stock.getBatch());
                    }

                    if (v.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "This item is currently unavailable");
                    } else {
                        cmbBoxBatch.setModel(new DefaultComboBoxModel<>(v));
                    }
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error loading item stock");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_cmbBoxSearchActionPerformed

    RoundedBalloonStyle style = new RoundedBalloonStyle(10, 8, Color.BLACK, Color.BLACK);
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (pay == 0.0) {
            BalloonTip tip = new BalloonTip(txtPayment, "<html><font color='white'>Please enter the paid amount</font></html>", style, false);
            tip.setVisible(true);
            TimingUtils.showTimedBalloon(tip, 2000);
            txtPayment.grabFocus();
            txtPayment.selectAll();

        } else {
            saveData();
            clear();
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbBoxBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxBatchActionPerformed


    }//GEN-LAST:event_cmbBoxBatchActionPerformed

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained

        int r = jTable1.getRowCount();
        if (r == 0) {
            btnUpdateQty.setEnabled(false);
        } else {
            btnUpdateQty.setEnabled(true);
        }
    }//GEN-LAST:event_jTable1FocusGained

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost

//        btnUpdateQty.setEnabled(false);
    }//GEN-LAST:event_jTable1FocusLost

    private void btnUpdateQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateQtyActionPerformed

        try {
            int r = jTable1.getSelectedRow();
            if (r == -1) {
                if (jTable1.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "There are no items in the table");
                } else {
                    JOptionPane.showMessageDialog(this, "Please select an item in the table");
                }
                return;
            }

            int itemId = Integer.parseInt(jTable1.getValueAt(r, 0).toString());
            String batch = jTable1.getValueAt(r, 2).toString();

            try (Session session = sf.openSession()) {

                // Use get() instead of load() — returns null safely if not found
                Item item = session.get(Item.class, itemId);
                if (item == null) {
                    JOptionPane.showMessageDialog(this, "Item not found");
                    return;
                }

                Stock st = session.createQuery(
                        "FROM Stock s WHERE s.item = :item AND s.batch = :batch",
                        Stock.class)
                        .setParameter("item", item)
                        .setParameter("batch", batch)
                        .uniqueResult();

                if (st == null) {
                    JOptionPane.showMessageDialog(this, "Stock record not found for selected item and batch");
                    return;
                }

                String input = JOptionPane.showInputDialog(this,
                        "Please enter the amount\nMax: " + st.getQty());
                if (input == null || input.trim().isEmpty()) {
                    return;  // User cancelled the dialog
                }

                int qt = Integer.parseInt(input.trim());

                if (qt > st.getQty()) {
                    JOptionPane.showMessageDialog(this,
                            "You cannot exceed the current stock amount.\n"
                            + "Current stock: " + st.getQty());
                } else {
                    double price = Double.parseDouble(jTable1.getValueAt(r, 3).toString());
                    jTable1.setValueAt(qt, r, 4);
                    jTable1.setValueAt(qt * price, r, 5);
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An unexpected error occurred");
            e.printStackTrace();
        }

        setFooter();
        System.gc();
    }//GEN-LAST:event_btnUpdateQtyActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

        int r = jTable1.getSelectedRow();
        if (r == -1) {
            return;
        }

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        try (Session session = sf.openSession()) {

            int itemId = Integer.parseInt(jTable1.getValueAt(r, 0).toString());
            String batch = jTable1.getValueAt(r, 2).toString();

            Item item = session.get(Item.class, itemId);
            if (item == null) {
                JOptionPane.showMessageDialog(this, "Item not found");
                return;
            }

            Stock s = session.createQuery(
                    "FROM Stock s WHERE s.item = :item AND s.batch = :batch",
                    Stock.class)
                    .setParameter("item", item)
                    .setParameter("batch", batch)
                    .uniqueResult();

            if (s == null) {
                JOptionPane.showMessageDialog(this, "Stock record not found");
                return;
            }

            int currentQty = Integer.parseInt(jTable1.getValueAt(r, 4).toString());
            double price = Double.parseDouble(jTable1.getValueAt(r, 3).toString());

            if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
                removeItems(dtm);

            } else if (evt.getKeyChar() == '+') {
                if (currentQty >= s.getQty()) {
                    evt.consume();
                    JOptionPane.showMessageDialog(this, "Maximum stock quantity reached.\nMax: " + s.getQty());
                } else {
                    int newQty = currentQty + 1;
                    jTable1.setValueAt(newQty, r, 4);
                    jTable1.setValueAt(newQty * price, r, 5);
                }

            } else if (evt.getKeyChar() == '-') {
                if (currentQty <= 1) {
                    evt.consume();
                } else {
                    int newQty = currentQty - 1;
                    jTable1.setValueAt(newQty, r, 4);
                    jTable1.setValueAt(newQty * price, r, 5);
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid value in table");
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An unexpected error occurred");
            e.printStackTrace();
        }

        setFooter();
    }//GEN-LAST:event_jTable1KeyPressed

    public void removeItems(DefaultTableModel dtm) throws HeadlessException {
        try {
            int r = jTable1.getSelectedRow();
            dtm.removeRow(r);
            setFooter();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please select an item to remove from invoice");
        }
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        removeItems(dtm);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnSavePrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePrintActionPerformed

        System.out.println(pay);
        if (pay == 0.0) {
            BalloonTip tip = new BalloonTip(txtPayment, "<html><font color='white'>Please enter the paid amount</font></html>", style, false);
            tip.setVisible(true);
            TimingUtils.showTimedBalloon(tip, 2000);
            txtPayment.grabFocus();
            txtPayment.selectAll();

        } else {
            saveData();
            printInvoice();
            clear();
        }
    }

    private void printInvoice() {
        new Thread(() -> {
            try (Session session = sf.openSession()) {

                // Get the latest invoice number using HQL aggregate
                Integer latestInvoiceNo = session.createQuery(
                        "SELECT MAX(i.invoiceinfo.invoiceNo) FROM Invoice i",
                        Integer.class)
                        .uniqueResult();

                if (latestInvoiceNo == null) {
                    JOptionPane.showMessageDialog(null, "No invoices found");
                    return;
                }

                // Build report parameters
                Map<String, Object> map = new HashMap<>();
                map.put("invoiceId", latestInvoiceNo);
                map.put("BusinessName", "Upul Hardware");
                map.put("BusinessAddress", "Nikaweratia");
                map.put("IS_IGNORE_PAGINATION", true);

                // Load report from classpath resources instead of hardcoded absolute path
                String reportPath = getClass()
                        .getResource("/reports/invoice703.jrxml")
                        .getPath();

                JasperReport report = JasperCompileManager.compileReport(reportPath);

                try (Connection cn = new Conn().con()) {
                    JasperPrint print = JasperFillManager.fillReport(report, map, cn);
                    JasperViewer.viewReport(print, true);
                }

            } catch (ExceptionInInitializerError e) {
                System.err.println("=== JasperReports init failure ===");
                e.getCause().printStackTrace();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Could not print the receipt");
                ex.printStackTrace();
            }
        }).start();
    }//GEN-LAST:event_btnSavePrintActionPerformed

    private void txtDiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscountKeyReleased

        setFooter();
    }//GEN-LAST:event_txtDiscountKeyReleased

    private void txtPaymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaymentKeyReleased

        setFooter();
    }//GEN-LAST:event_txtPaymentKeyReleased

    private void jSpinner1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner1KeyReleased

    }//GEN-LAST:event_jSpinner1KeyReleased

    Locale l = new Locale("si", "LK");
    NumberFormat f = NumberFormat.getCurrencyInstance(l);

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

        setTableValues();
    }//GEN-LAST:event_formFocusGained

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained

        jTextField1.selectAll();
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String input = jTextField1.getText().trim();
            if (input.isEmpty()) {
                return;
            }

            try (Session session = sf.openSession()) {
                int itemId = Integer.parseInt(input);

                Item itm = session.get(Item.class, itemId);
                if (itm == null) {
                    JOptionPane.showMessageDialog(this, "Cannot find item");
                    return;
                }

                if (!itm.getStat().equals("active")) {
                    JOptionPane.showMessageDialog(this, "This item has been removed from stock");
                } else {
                    cmbBoxSearch.setSelectedItem(itm.getItemName());
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please enter a valid item ID");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Cannot find item");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing

        int x = jTable1.getRowCount();
        if (x >= 1) {
            int i = JOptionPane.showConfirmDialog(this, "Do you want to cancel the invoice?");
            if (i == 0) {
                this.dispose();
            }
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_formInternalFrameClosing

    public void setFooter() {
        int r = jTable1.getRowCount();
        int c = jTable1.getColumnCount();
        tot = 0;
        for (int i = 0; i < r; i++) {
            int qt = Integer.parseInt(jTable1.getValueAt(i, 4).toString());
            double total = Double.parseDouble(jTable1.getValueAt(i, 3).toString().replace(",", "")) * qt;

            tot += total;
        }
        lblSubTotal.setText(f.format(tot));

        try {
            dis = Double.parseDouble(txtDiscount.getText());
            pay = Double.parseDouble(txtPayment.getText());
        } catch (Exception e) {
            dis = 0.0;
            pay = 0.0;
        }
        lblTotal.setText(f.format((tot) - (dis)));
        lblBalance.setText(f.format((pay) - (tot - dis)));

    }

    public void saveData() {
        try (Session session = sf.openSession()) {

            // ── 1. Save the invoice header (Invoiceinfo) ────────────────────────
            Transaction trans = session.beginTransaction();
            Invoiceinfo info = new Invoiceinfo();
            info.setDate(new Date(System.currentTimeMillis()));
            info.setNetTotal(tot);
            info.setStat("delivered");
            info.setPaid(Double.parseDouble(txtPayment.getValue().toString()));
            info.setDiscount(dis == 0.0 ? 0.0
                    : Double.parseDouble(txtDiscount.getValue().toString()));
            session.persist(info);
            trans.commit();

            // ── 2. Reload the saved Invoiceinfo using its generated ID ──────────
            // info.getInvoiceNo() is now populated after persist + commit
            Integer newInvoiceNo = session.createQuery(
                    "SELECT MAX(i.invoiceNo) FROM Invoiceinfo i",
                    Integer.class)
                    .uniqueResult();

            if (newInvoiceNo == null) {
                JOptionPane.showMessageDialog(this, "Failed to retrieve saved invoice");
                return;
            }

            Invoiceinfo savedInfo = session.get(Invoiceinfo.class, newInvoiceNo);
            if (savedInfo == null) {
                JOptionPane.showMessageDialog(this, "Failed to load saved invoice");
                return;
            }

            // ── 3. Save each invoice line from the table ─────────────────────────
            int rowCount = jTable1.getRowCount();
            for (int i = 0; i < rowCount; i++) {

                int itemId = Integer.parseInt(
                        jTable1.getValueAt(i, 0).toString().replace(",", ""));
                String batch = jTable1.getValueAt(i, 2).toString();
                int qty = Integer.parseInt(
                        jTable1.getValueAt(i, 4).toString().replace(",", ""));
                double subTotal = Double.parseDouble(
                        jTable1.getValueAt(i, 5).toString().replace(",", ""));

                // Load item
                Item item = session.get(Item.class, itemId);
                if (item == null) {
                    JOptionPane.showMessageDialog(this, "Item not found for row " + (i + 1));
                    continue;
                }

                // Load matching stock record
                Stock stock = session.createQuery(
                        "FROM Stock s WHERE s.item = :item AND s.batch = :batch",
                        Stock.class)
                        .setParameter("item", item)
                        .setParameter("batch", batch)
                        .uniqueResult();

                if (stock == null) {
                    JOptionPane.showMessageDialog(this, "Stock not found for: "
                            + item.getItemName() + " / batch: " + batch);
                    continue;
                }

                // Save invoice line
                Transaction invoiceTrans = session.beginTransaction();
                com.olympus.system.hawkdeskpos.db.dao.Invoice invo
                        = new com.olympus.system.hawkdeskpos.db.dao.Invoice();
                invo.setInvoiceinfo(savedInfo);
                invo.setItem(item);
                invo.setStock(stock);
                invo.setBatch(batch);
                invo.setDateTime(new Date(System.currentTimeMillis()));
                invo.setQty((double) qty);
                invo.setSubTotal(subTotal);
                session.persist(invo);
                invoiceTrans.commit();

                // Update stock quantity
                Transaction stockTrans = session.beginTransaction();
                stock.setQty(stock.getQty() - qty);
                if (stock.getQty() <= 0) {
                    stock.setQty(0.0);
                    stock.setStat("un-available");
                }
                session.merge(stock);
                stockTrans.commit();
            }

            // ── 4. Post-save UI updates ──────────────────────────────────────────
            JOptionPane.showMessageDialog(this,
                    "Record saved.\nPlease give change: " + lblBalance.getText());
            jTextField1.setText("");
            jTextField1.grabFocus();
            Home.setNotifications();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid number format in table data");
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed to save invoice");
            e.printStackTrace();
        }
    }

    public void clear() {
        cmbBoxSearch.setSelectedIndex(0);
        cmbBoxBatch.setSelectedItem(" ");
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int r = jTable1.getRowCount();
        for (int i = 0; i < r; i++) {
            dtm.removeRow(0);

        }
        jTable1.setModel(dtm);
        lblBalance.setText("0.00");
        lblSubTotal.setText("0.00");
        lblTotal.setText("0.00");
        txtDiscount.setText("0.00");
        txtPayment.setText("0.00");
        cmbBoxBatch.removeAllItems();
        jSpinner1.setValue(Integer.valueOf("1"));
        qty = 0;
        product = 0;
        dis = 0.00;
        tot = 0.00;
        pay = 0.00;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSavePrint;
    private javax.swing.JButton btnUpdateQty;
    private javax.swing.JComboBox cmbBoxBatch;
    private javax.swing.JComboBox cmbBoxSearch;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JFormattedTextField txtDiscount;
    private javax.swing.JFormattedTextField txtPayment;
    // End of variables declaration//GEN-END:variables
}
