/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.olympus.system.hawkdeskpos.frontend.sale;

import java.awt.Image;
import java.awt.Color;
import com.olympus.system.hawkdeskpos.db.dao.Invoiceinfo;
import com.olympus.system.hawkdeskpos.db.dao.Item;
import com.olympus.system.hawkdeskpos.db.dao.Stock;
import com.olympus.system.hawkdeskpos.db.util.Controller;
import com.olympus.system.hawkdeskpos.frontend.Conn;
import com.olympus.system.hawkdeskpos.frontend.Home;
import com.olympus.system.hawkdeskpos.frontend.stock.AddStock;
import java.awt.Graphics;
import java.sql.Connection;
import java.awt.event.KeyEvent;
import java.awt.HeadlessException;
import java.beans.PropertyVetoException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.java.balloontip.BalloonTip;
import net.java.balloontip.styles.RoundedBalloonStyle;
import net.java.balloontip.utils.TimingUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import static org.hibernate.annotations.SourceType.DB;
import org.hibernate.criterion.Projections;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author Thusitha
 */
public class Invoice extends javax.swing.JInternalFrame {

    /**
     * Creates new form Invoice
     */
    SessionFactory sf = null;
    Session ses = null;

    double tot = 0;
    int qty = 0;
    int product = 0;
    double pay = 0.0;
    double dis = 0.0;

    public Invoice() {
        super("Invoice", true, true, true);
        initComponents();
        sf = Controller.getSessionFactory();
        ses = sf.openSession();
        setTableValues();
    }

    public void setTableValues() {
        Criteria cr = ses.createCriteria(Item.class);
        cr.add(Restrictions.eq("stat", "active"));
        ArrayList<Item> itm = (ArrayList<Item>) cr.list();
        Vector v = new Vector();
        v.add("-- Select Item --");
        for (int i = 0; i < itm.size(); i++) {
            Item item = itm.get(i);
            v.add(item.getItemName());
        }
        cmbBoxSearch.setModel(new DefaultComboBoxModel(v));

        System.gc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel(){

            private Image image;{
                try{
                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/back.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }
            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(), getHeight(), this);
            }
        };
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbBoxSearch = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cmbBoxBatch = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel(){

            private Image image;{
                try{
                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/back2.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }
            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(), getHeight(), this);
            }
        };
        btnUpdateQty = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel(){

            private Image image;{
                try{
                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/back.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }
            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(), getHeight(), this);
            }
        };
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnSavePrint = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPayment = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Invoice");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/sale.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Invoice");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Search Item");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Qty");

        cmbBoxSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbBoxSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Type to find items" }));
        cmbBoxSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxSearchActionPerformed(evt);
            }
        });

        jSpinner1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSpinner1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpinner1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSpinner1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinner1KeyTyped(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Select batch");

        cmbBoxBatch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbBoxBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxBatchActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setText("Type item id");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbBoxSearch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(cmbBoxBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbBoxSearch)
                            .addComponent(jTextField1)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(cmbBoxBatch)))
                .addGap(13, 13, 13))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnUpdateQty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUpdateQty.setText("Update Quantity");
        btnUpdateQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateQtyActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Remove Item");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateQty, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUpdateQty, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item #", "Item Name", "batch", "Item Price", "Qty", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(60);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(2).setMinWidth(100);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(3).setMinWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(4).setMinWidth(50);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(5).setMinWidth(100);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );

        jPanel5.setBackground(java.awt.SystemColor.window);

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnSavePrint.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSavePrint.setText("Save & Print");
        btnSavePrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePrintActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sub Total");

        lblSubTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubTotal.setText("0.00");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Discount");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtDiscount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtDiscount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDiscount.setText("0.00");
        txtDiscount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscountKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Total");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("0.00");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Balance");

        lblBalance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBalance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBalance.setText("0.00");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Payment");

        txtPayment.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtPayment.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPayment.setText("0.00");
        txtPayment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaymentKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(txtPayment))
                        .addGap(130, 130, 130)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnSavePrint, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblSubTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lblTotal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblBalance)
                    .addComponent(jLabel8)
                    .addComponent(txtPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSavePrint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner1KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Criteria cr = ses.createCriteria(Item.class);
            cr.add(Restrictions.eq("itemName", cmbBoxSearch.getSelectedItem().toString()));
            Item itm = (Item) cr.uniqueResult();

            Criteria cr2 = ses.createCriteria(Stock.class);
            cr2.add(Restrictions.and(Restrictions.eq("item", itm), Restrictions.eq("batch", cmbBoxBatch.getSelectedItem().toString())));
            Stock stk = (Stock) cr.uniqueResult();

            if (stk.getQty() < Integer.parseInt(jSpinner1.getValue().toString())) {
                JOptionPane.showMessageDialog(this, itm.getItemName() + " has not that much stock according to selected batch.\n Please select another batch\n Max:" + stk.getQty());
            }
        }
    }//GEN-LAST:event_jSpinner1KeyPressed

    private void jSpinner1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner1KeyTyped


    }//GEN-LAST:event_jSpinner1KeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            Criteria cr = ses.createCriteria(Item.class);
            cr.add(Restrictions.eq("itemName", cmbBoxSearch.getSelectedItem().toString()));
            Item itm = (Item) cr.uniqueResult();

            Criteria cr2 = ses.createCriteria(Stock.class);
            cr2.add(Restrictions.and(Restrictions.eq("item", itm), Restrictions.eq("batch", cmbBoxBatch.getSelectedItem().toString())));
            Stock st = (Stock) cr2.uniqueResult();

            int r = jTable1.getRowCount();
            int q = 0;
            boolean item = false;
            int ir = 0;
            for (int i = 0; i < r; i++) {
                if (jTable1.getValueAt(i, 1).equals(cmbBoxSearch.getSelectedItem()) && jTable1.getValueAt(i, 2).equals(cmbBoxBatch.getSelectedItem())) {
                    q += Integer.parseInt(jTable1.getValueAt(i, 4).toString());
                    item = true;
                    ir = i;
                }
            }

            if (item == true) {
                if (q + Integer.parseInt(jSpinner1.getValue().toString()) > st.getQty()) {
                    JOptionPane.showMessageDialog(this, itm.getItemName() + " has not that much stock according to selected batch.\n Please select another batch\n Max:" + st.getQty());

                } else {
                    jTable1.setValueAt(Integer.parseInt(jTable1.getValueAt(ir, 4).toString()) + Integer.parseInt(jSpinner1.getValue().toString()), ir, 4);
                }
            } else if (st.getQty() >= Integer.parseInt(jSpinner1.getValue().toString())) {

                Vector v = new Vector();

                NumberFormat f = NumberFormat.getInstance();
                f.setMinimumFractionDigits(2);

                v.add(itm.getItemId());
                v.add(itm.getItemName());
                v.add(st.getBatch());
                v.add(f.format(st.getPrice()));
                v.add(jSpinner1.getValue());
                v.add(f.format(st.getPrice() * Integer.parseInt(jSpinner1.getValue().toString())));

                dtm.addRow(v);

                jTable1.setModel(dtm);
            } else {
                JOptionPane.showMessageDialog(this, itm.getItemName() + " has not that much stock according to selected batch.\n Please select another batch\n Max:" + st.getQty());
                jSpinner1.setValue(st.getQty());

            }

            setFooter();
            System.gc();
        } catch (NullPointerException e) {
            RoundedBalloonStyle style = new RoundedBalloonStyle(10, 8, Color.BLACK, Color.BLACK);
            BalloonTip tip = new BalloonTip(cmbBoxSearch, "<html><font color='white'>Please Select an item</font></html>", style, false);
            tip.setVisible(true);
            TimingUtils.showTimedBalloon(tip, 2000);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmbBoxSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxSearchActionPerformed

        if (cmbBoxSearch.getSelectedIndex() != 0) {
            Criteria cr = ses.createCriteria(Item.class);
            cr.add(Restrictions.eq("itemName", cmbBoxSearch.getSelectedItem().toString()));
            Item itm = (Item) cr.uniqueResult();

            Criteria cr2 = ses.createCriteria(Stock.class);
            cr2.add(Restrictions.eq("item", itm));
            cr2.add(Restrictions.eq("stat", "available"));
            ArrayList<Stock> lst = (ArrayList<Stock>) cr2.list();
            Vector v = new Vector();

            if (lst.isEmpty()) {
                int i = JOptionPane.showConfirmDialog(this, "Currently this item not in the stock. Do you want to add stock?", "Add new Stock", JOptionPane.YES_NO_OPTION);
                if (i == 0) {
                    Item item = (Item) ses.load(Item.class, Integer.parseInt(jTextField1.getText()));
                    AddStock addStk = new AddStock(item);
                    Home.HomeDeskpane.add(addStk);
                    addStk.setVisible(true);
                    try {
                        addStk.setMaximum(true);
                    } catch (PropertyVetoException ex) {
                        Logger.getLogger(Invoice.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                for (int i = 0; i < lst.size(); i++) {
                    Stock stock = lst.get(i);

                    if (stock.getStat().equals("available")) {
                        v.add(stock.getBatch());
                    }
                }
                if (v.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "This item currently un-available");
                }
                cmbBoxBatch.setModel(new DefaultComboBoxModel(v));
            }
        }
    }//GEN-LAST:event_cmbBoxSearchActionPerformed

    RoundedBalloonStyle style = new RoundedBalloonStyle(10, 8, Color.BLACK, Color.BLACK);
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (pay == 0.0) {
            BalloonTip tip = new BalloonTip(txtPayment, "<html><font color='white'>Please enter the paid amount</font></html>", style, false);
            tip.setVisible(true);
            TimingUtils.showTimedBalloon(tip, 2000);
            txtPayment.grabFocus();
            txtPayment.selectAll();

        } else {
            saveData();
            clear();
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbBoxBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxBatchActionPerformed


    }//GEN-LAST:event_cmbBoxBatchActionPerformed

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained

        int r = jTable1.getRowCount();
        if (r == 0) {
            btnUpdateQty.setEnabled(false);
        } else {
            btnUpdateQty.setEnabled(true);
        }
    }//GEN-LAST:event_jTable1FocusGained

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost

//        btnUpdateQty.setEnabled(false);
    }//GEN-LAST:event_jTable1FocusLost

    private void btnUpdateQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateQtyActionPerformed

        try {
            int r = jTable1.getSelectedRow();

            int i = Integer.parseInt(jTable1.getValueAt(r, 0).toString());
            String bt = jTable1.getValueAt(r, 2).toString();
            Item item = (Item) ses.load(Item.class, i);
            Criteria cr = ses.createCriteria(Stock.class);
            cr.add(Restrictions.and(Restrictions.eq("item", item), Restrictions.eq("batch", bt)));
            Stock st = (Stock) cr.uniqueResult();
            int qt = Integer.parseInt(JOptionPane.showInputDialog(this, "Please enter the amount\n Max:" + st.getQty()));
            int cQt = st.getQty();

            if (qt > cQt) {
                JOptionPane.showMessageDialog(this, "You cannot exceed current stock amount.\n Current stock:" + st.getQty());
            } else {
                jTable1.setValueAt(qt, r, 4);
                jTable1.setValueAt(qt * Double.parseDouble(jTable1.getValueAt(r, 3).toString()), r, 5);
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            int r = jTable1.getRowCount();
            if (r == 0) {
                JOptionPane.showMessageDialog(this, "There is no item in the table");
            } else {
                JOptionPane.showMessageDialog(this, "Please select a item in the table");
            }
        } catch (NullPointerException n) {
        } catch (Exception e) {
        }
        setFooter();
        System.gc();
    }//GEN-LAST:event_btnUpdateQtyActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        int r = jTable1.getSelectedRow();
        Criteria cr = ses.createCriteria(Stock.class);
        cr.add(Restrictions.and(Restrictions.eq("item", (Item) ses.load(Item.class, Integer.parseInt(jTable1.getValueAt(r, 0).toString()))), Restrictions.eq("batch", jTable1.getValueAt(r, 2))));
        Stock s = (Stock) cr.uniqueResult();
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            removeItems(dtm);
        } else if (evt.getKeyChar() == '+') {
            if (s.getQty() <= Integer.parseInt(jTable1.getValueAt(r, 4).toString())) {
                evt.consume();
                JOptionPane.showMessageDialog(this, "Maximum stock qty reached");
            } else {
                jTable1.setValueAt(Integer.parseInt(jTable1.getValueAt(r, 4).toString()) + 1, r, 4);
            }
        } else if (evt.getKeyChar() == '-') {
            if (Integer.parseInt(jTable1.getValueAt(r, 4).toString()) == 1) {
                evt.consume();
            } else {
                jTable1.setValueAt(Integer.parseInt(jTable1.getValueAt(r, 4).toString()) - 1, r, 4);

            }
        }
        setFooter();
    }//GEN-LAST:event_jTable1KeyPressed

    public void removeItems(DefaultTableModel dtm) throws HeadlessException {
        try {
            int r = jTable1.getSelectedRow();
            dtm.removeRow(r);
            setFooter();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please select an item to remove from invoice");
        }
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        removeItems(dtm);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnSavePrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePrintActionPerformed

        System.out.println(pay);
        if (pay == 0.0) {
            BalloonTip tip = new BalloonTip(txtPayment, "<html><font color='white'>Please enter the paid amount</font></html>", style, false);
            tip.setVisible(true);
            TimingUtils.showTimedBalloon(tip, 2000);
            txtPayment.grabFocus();
            txtPayment.selectAll();

        } else {
            saveData();
            printInvoice();
            clear();
        }
    }

    private void printInvoice() {
        new Thread(
                new Runnable() {

                    @Override
                    public void run() {

                        try {
                            Criteria cr = ses.createCriteria(com.olympus.system.hawkdeskpos.db.dao.Invoice.class);
                            cr.setProjection(Projections.max("invoiceinfo"));
                            Invoiceinfo in = (Invoiceinfo) cr.uniqueResult();
                            int i = in.getInvoiceNo();

                            Connection cn = new Conn().con();
//                            JRProperties.setProperty("net.sf.jasperreports.xpath.executer.factory", "net.sf.jasperreports.engine.util.xml.JaxenXPathExecuterFactory");
//                            JRProperties.setProperty("net.sf.jasperreports.xpath.executer.factory", "net.sf.jasperreports.engine.util.xml.JaxenXPathExecuterFactory");
                            Class.forName("net.sf.jasperreports.extensions.ExtensionsEnvironment");
                            Map<String, Object> map = new HashMap<String, Object>();
                            map.put("invoiceId", i);
                            map.put("BusinessName", "Upul Hardware");
                            map.put("BusinessAddress", "Nikaweratia");
                            map.put("IS_IGNORE_PAGINATION", true);
//                            JasperReport report = JasperCompileManager.compileReport("D:\\Dev\\Workspaces\\NetBeans\\Products\\Pharmacy\\src\\reports\\Invoice.jrxml");
                            JasperReport report = JasperCompileManager.compileReport("D:\\Dev\\Workspaces\\NetBeans\\Products\\Pharmacy\\src\\reports\\invoice703.jrxml");
                            JasperPrint print = JasperFillManager.fillReport(report, map, cn);
                            JasperViewer.viewReport(print, true);
//                            JasperPrintManager.printReport(print, false);

                        }catch (ExceptionInInitializerError e) {
                            System.out.println("=== REAL CAUSE ===");
                            e.getCause().printStackTrace();  // This prints the actual crash
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, "Note: You did't print the reciept");
                            ex.printStackTrace();
                        }
                    }
                }
        ).start();
    }//GEN-LAST:event_btnSavePrintActionPerformed

    private void txtDiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscountKeyReleased

        setFooter();
    }//GEN-LAST:event_txtDiscountKeyReleased

    private void txtPaymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaymentKeyReleased

        setFooter();
    }//GEN-LAST:event_txtPaymentKeyReleased

    private void jSpinner1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner1KeyReleased

    }//GEN-LAST:event_jSpinner1KeyReleased

    Locale l = new Locale("si", "LK");
    NumberFormat f = NumberFormat.getCurrencyInstance(l);

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

        setTableValues();
    }//GEN-LAST:event_formFocusGained

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained

        jTextField1.selectAll();
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                Item itm = (Item) ses.load(Item.class, Integer.parseInt(jTextField1.getText()));
                if (!itm.getStat().equals("active")) {
                    JOptionPane.showMessageDialog(this, "Entered item delete from the stock");
                } else {
                    cmbBoxSearch.setSelectedItem(itm.getItemName());
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Cannot find item");
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing

        int x = jTable1.getRowCount();
        if (x >= 1) {
            int i = JOptionPane.showConfirmDialog(this, "Do you want to cancel the invoice?");
            if (i == 0) {
                this.dispose();
            }
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_formInternalFrameClosing

    public void setFooter() {
        int r = jTable1.getRowCount();
        int c = jTable1.getColumnCount();
        tot = 0;
        for (int i = 0; i < r; i++) {
            int qt = Integer.parseInt(jTable1.getValueAt(i, 4).toString());
            double total = Double.parseDouble(jTable1.getValueAt(i, 3).toString().replace(",","")) * qt;

            tot += total;
        }
        lblSubTotal.setText(f.format(tot));

        try {
            dis = Double.parseDouble(txtDiscount.getText());
            pay = Double.parseDouble(txtPayment.getText());
        } catch (Exception e) {
            dis = 0.0;
            pay = 0.0;
        }
        lblTotal.setText(f.format((tot) - (dis)));
        lblBalance.setText(f.format((pay) - (tot - dis)));

    }

    public void saveData() {
        Invoiceinfo info = new Invoiceinfo();
        Transaction trans = ses.beginTransaction();
        info.setDate(new Date(System.currentTimeMillis()));
        info.setTotal(tot);
        info.setStat("delievered");
        info.setPaid(Double.parseDouble(txtPayment.getValue().toString()));
        if (dis == 0.0) {
            info.setDiscount(0.0);
        } else {
            info.setDiscount(Double.parseDouble(txtDiscount.getValue().toString()));
        }
        ses.save(info);
        trans.commit();

        Criteria cr = ses.createCriteria(Invoiceinfo.class);
        cr.setProjection(Projections.count("invoiceNo"));
        long l = (long) cr.uniqueResult();
        System.out.println(l);

        int r = jTable1.getRowCount();
        int c = jTable1.getColumnCount();

        System.out.println("before loops");

        for (int i = 0; i < r; i++) {
            Criteria cIn = ses.createCriteria(Invoiceinfo.class);
            cIn.setProjection(Projections.max("invoiceNo"));
            Invoiceinfo inv = (Invoiceinfo) ses.load(Invoiceinfo.class, (int) cIn.uniqueResult());

            Transaction tran = ses.beginTransaction();
            com.olympus.system.hawkdeskpos.db.dao.Invoice invo = new com.olympus.system.hawkdeskpos.db.dao.Invoice();
            for (int j = 0; j < c; j++) {
                if (j == 0) {
                    System.out.println("in 0");
                    Item it = (Item) ses.load(Item.class, Integer.parseInt(jTable1.getValueAt(i, j).toString()));
                    invo.setInvoiceinfo(inv);
                    invo.setItem(it);
                    System.out.println(it.getItemName());
                } else if (j == 2) {
                    System.out.println("in 2");
                    invo.setBatch(jTable1.getValueAt(i, j).toString());
                } else if (j == 3) {
                    System.out.println("in 3");
                    invo.setDateTime(new Date(System.currentTimeMillis()));
                } else if (j == 4) {
                    invo.setQty(Integer.parseInt(jTable1.getValueAt(i, j).toString().replace(",", "")));
                } else if (j == 5) {

                    Item it = (Item) ses.load(Item.class, Integer.parseInt(jTable1.getValueAt(i, 0).toString().replace(",", "")));
                    Criteria stock = ses.createCriteria(Stock.class);
                    stock.add(Restrictions.and(Restrictions.eq("item", it), Restrictions.eq("batch", jTable1.getValueAt(i, 2).toString())));
                    Stock s = (Stock) stock.uniqueResult();
                    System.out.println(s.getStockId());
                    invo.setStock(s);
                    invo.setSubTotal(Double.parseDouble(jTable1.getValueAt(i, j).toString().replace(",", "")));
                    ses.save(invo);
                    tran.commit();

                    Transaction stTr = ses.beginTransaction();
                    s.setQty(s.getQty() - (Integer.parseInt(jTable1.getValueAt(i, 4).toString().replace(",", ""))));
                    int x = s.getQty();
                    if (x == 0) {
                        s.setStat("un-available");
                    }
                    ses.saveOrUpdate(s);
                    stTr.commit();

                }
            }

            JOptionPane.showMessageDialog(this, "Record Saved. \n Please give change:" + lblBalance.getText());
            jTextField1.setText("");
            jTextField1.grabFocus();
            Home.setNotifications();
        }

    }

    public void clear() {
        cmbBoxSearch.setSelectedIndex(0);
        cmbBoxBatch.setSelectedItem(" ");
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int r = jTable1.getRowCount();
        for (int i = 0; i < r; i++) {
            dtm.removeRow(0);

        }
        jTable1.setModel(dtm);
        lblBalance.setText("0.00");
        lblSubTotal.setText("0.00");
        lblTotal.setText("0.00");
        txtDiscount.setText("0.00");
        txtPayment.setText("0.00");
        cmbBoxBatch.removeAllItems();
        jSpinner1.setValue(Integer.valueOf("1"));
        qty = 0;
        product = 0;
        dis = 0.00;
        tot = 0.00;
        pay = 0.00;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSavePrint;
    private javax.swing.JButton btnUpdateQty;
    private javax.swing.JComboBox cmbBoxBatch;
    private javax.swing.JComboBox cmbBoxSearch;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JFormattedTextField txtDiscount;
    private javax.swing.JFormattedTextField txtPayment;
    // End of variables declaration//GEN-END:variables
}
