package com.olympus.system.hawkdeskpos.db.dao;
// Generated Oct 23, 2014 10:01:37 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer catId;
     private String categoryName;
     private String stat;
     private Set items = new HashSet(0);

    public Category() {
    }

    public Category(String categoryName, String stat, Set items) {
       this.categoryName = categoryName;
       this.stat = stat;
       this.items = items;
    }
   
    public Integer getCatId() {
        return this.catId;
    }
    
    public void setCatId(Integer catId) {
        this.catId = catId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public String getStat() {
        return this.stat;
    }
    
    public void setStat(String stat) {
        this.stat = stat;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


