package com.olympus.system.hawkdeskpos.db.dao;
// Generated Oct 23, 2014 10:01:37 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Grn generated by hbm2java
 */
public class Grn  implements java.io.Serializable {


     private Integer no;
     private Item item;
     private Grninfo grninfo;
     private Date expireDate;
     private Integer itemQty;
     private Double itemCost;
     private Double itemPrice;

    public Grn() {
    }

	
    public Grn(Item item, Grninfo grninfo) {
        this.item = item;
        this.grninfo = grninfo;
    }
    public Grn(Item item, Grninfo grninfo, Date expireDate, Integer itemQty, Double itemCost, Double itemPrice) {
       this.item = item;
       this.grninfo = grninfo;
       this.expireDate = expireDate;
       this.itemQty = itemQty;
       this.itemCost = itemCost;
       this.itemPrice = itemPrice;
    }
   
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Grninfo getGrninfo() {
        return this.grninfo;
    }
    
    public void setGrninfo(Grninfo grninfo) {
        this.grninfo = grninfo;
    }
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }
    public Integer getItemQty() {
        return this.itemQty;
    }
    
    public void setItemQty(Integer itemQty) {
        this.itemQty = itemQty;
    }
    public Double getItemCost() {
        return this.itemCost;
    }
    
    public void setItemCost(Double itemCost) {
        this.itemCost = itemCost;
    }
    public Double getItemPrice() {
        return this.itemPrice;
    }
    
    public void setItemPrice(Double itemPrice) {
        this.itemPrice = itemPrice;
    }




}


