package com.olympus.system.hawkdeskpos.db.dao;
// Generated Oct 23, 2014 10:01:37 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Grninfo generated by hbm2java
 */
public class Grninfo  implements java.io.Serializable {


     private Integer grnNo;
     private Date date;
     private Double subTotal;
     private Set stocks = new HashSet(0);
     private Set grns = new HashSet(0);

    public Grninfo() {
    }

    public Grninfo(Date date, Double subTotal, Set stocks, Set grns) {
       this.date = date;
       this.subTotal = subTotal;
       this.stocks = stocks;
       this.grns = grns;
    }
   
    public Integer getGrnNo() {
        return this.grnNo;
    }
    
    public void setGrnNo(Integer grnNo) {
        this.grnNo = grnNo;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(Double subTotal) {
        this.subTotal = subTotal;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }
    public Set getGrns() {
        return this.grns;
    }
    
    public void setGrns(Set grns) {
        this.grns = grns;
    }




}


