package com.olympus.system.hawkdeskpos.db.dao;
// Generated Oct 23, 2014 10:01:37 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer id;
     private Stock stock;
     private Item item;
     private Invoiceinfo invoiceinfo;
     private String batch;
     private Date dateTime;
     private Integer qty;
     private Double subTotal;

    public Invoice() {
    }

	
    public Invoice(Stock stock, Item item, Invoiceinfo invoiceinfo) {
        this.stock = stock;
        this.item = item;
        this.invoiceinfo = invoiceinfo;
    }
    public Invoice(Stock stock, Item item, Invoiceinfo invoiceinfo, String batch, Date dateTime, Integer qty, Double subTotal) {
       this.stock = stock;
       this.item = item;
       this.invoiceinfo = invoiceinfo;
       this.batch = batch;
       this.dateTime = dateTime;
       this.qty = qty;
       this.subTotal = subTotal;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Invoiceinfo getInvoiceinfo() {
        return this.invoiceinfo;
    }
    
    public void setInvoiceinfo(Invoiceinfo invoiceinfo) {
        this.invoiceinfo = invoiceinfo;
    }
    public String getBatch() {
        return this.batch;
    }
    
    public void setBatch(String batch) {
        this.batch = batch;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(Double subTotal) {
        this.subTotal = subTotal;
    }




}


