package com.olympus.system.hawkdeskpos.db.dao;
// Generated Oct 23, 2014 10:01:37 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoiceinfo generated by hbm2java
 */
public class Invoiceinfo  implements java.io.Serializable {


     private Integer invoiceNo;
     private Date date;
     private Double total;
     private String stat;
     private Double paid;
     private Double discount;
     private Set invoices = new HashSet(0);
     private Set returns = new HashSet(0);

    public Invoiceinfo() {
    }

    public Invoiceinfo(Date date, Double total, String stat, Double paid, Double discount, Set invoices, Set returns) {
       this.date = date;
       this.total = total;
       this.stat = stat;
       this.paid = paid;
       this.discount = discount;
       this.invoices = invoices;
       this.returns = returns;
    }
   
    public Integer getInvoiceNo() {
        return this.invoiceNo;
    }
    
    public void setInvoiceNo(Integer invoiceNo) {
        this.invoiceNo = invoiceNo;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public String getStat() {
        return this.stat;
    }
    
    public void setStat(String stat) {
        this.stat = stat;
    }
    public Double getPaid() {
        return this.paid;
    }
    
    public void setPaid(Double paid) {
        this.paid = paid;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }
    public Set getReturns() {
        return this.returns;
    }
    
    public void setReturns(Set returns) {
        this.returns = returns;
    }




}


