package com.olympus.system.hawkdeskpos.db.dao;
// Generated Oct 23, 2014 10:01:37 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private Integer itemId;
     private Category category;
     private Brands brands;
     private String itemName;
     private Integer minLevel;
     private String stat;
     private Set stocks = new HashSet(0);
     private Set invoices = new HashSet(0);
     private Set grns = new HashSet(0);

    public Item() {
    }

	
    public Item(Category category, Brands brands) {
        this.category = category;
        this.brands = brands;
    }
    public Item(Category category, Brands brands, String itemName, Integer minLevel, String stat, Set stocks, Set invoices, Set grns) {
       this.category = category;
       this.brands = brands;
       this.itemName = itemName;
       this.minLevel = minLevel;
       this.stat = stat;
       this.stocks = stocks;
       this.invoices = invoices;
       this.grns = grns;
    }
   
    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Brands getBrands() {
        return this.brands;
    }
    
    public void setBrands(Brands brands) {
        this.brands = brands;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public Integer getMinLevel() {
        return this.minLevel;
    }
    
    public void setMinLevel(Integer minLevel) {
        this.minLevel = minLevel;
    }
    public String getStat() {
        return this.stat;
    }
    
    public void setStat(String stat) {
        this.stat = stat;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }
    public Set getGrns() {
        return this.grns;
    }
    
    public void setGrns(Set grns) {
        this.grns = grns;
    }




}


