package com.olympus.system.hawkdeskpos.db.dao;
// Generated Oct 23, 2014 10:01:37 PM by Hibernate Tools 3.6.0



/**
 * Return generated by hbm2java
 */
public class Return  implements java.io.Serializable {


     private Integer returnId;
     private Invoiceinfo invoiceinfo;
     private Integer qty;
     private String reson;
     private Integer returnTo;
     private String stat;

    public Return() {
    }

	
    public Return(Invoiceinfo invoiceinfo) {
        this.invoiceinfo = invoiceinfo;
    }
    public Return(Invoiceinfo invoiceinfo, Integer qty, String reson, Integer returnTo, String stat) {
       this.invoiceinfo = invoiceinfo;
       this.qty = qty;
       this.reson = reson;
       this.returnTo = returnTo;
       this.stat = stat;
    }
   
    public Integer getReturnId() {
        return this.returnId;
    }
    
    public void setReturnId(Integer returnId) {
        this.returnId = returnId;
    }
    public Invoiceinfo getInvoiceinfo() {
        return this.invoiceinfo;
    }
    
    public void setInvoiceinfo(Invoiceinfo invoiceinfo) {
        this.invoiceinfo = invoiceinfo;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public String getReson() {
        return this.reson;
    }
    
    public void setReson(String reson) {
        this.reson = reson;
    }
    public Integer getReturnTo() {
        return this.returnTo;
    }
    
    public void setReturnTo(Integer returnTo) {
        this.returnTo = returnTo;
    }
    public String getStat() {
        return this.stat;
    }
    
    public void setStat(String stat) {
        this.stat = stat;
    }




}


