package com.olympus.system.hawkdeskpos.db.dao;
// Generated Oct 23, 2014 10:01:37 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private Integer stockId;
     private Item item;
     private Grninfo grninfo;
     private String batch;
     private Date expireDate;
     private Integer qty;
     private Double cost;
     private Double price;
     private String stat;
     private Set invoices = new HashSet(0);

    public Stock() {
    }

	
    public Stock(Item item, Grninfo grninfo) {
        this.item = item;
        this.grninfo = grninfo;
    }
    public Stock(Item item, Grninfo grninfo, String batch, Date expireDate, Integer qty, Double cost, Double price, String stat, Set invoices) {
       this.item = item;
       this.grninfo = grninfo;
       this.batch = batch;
       this.expireDate = expireDate;
       this.qty = qty;
       this.cost = cost;
       this.price = price;
       this.stat = stat;
       this.invoices = invoices;
    }
   
    public Integer getStockId() {
        return this.stockId;
    }
    
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Grninfo getGrninfo() {
        return this.grninfo;
    }
    
    public void setGrninfo(Grninfo grninfo) {
        this.grninfo = grninfo;
    }
    public String getBatch() {
        return this.batch;
    }
    
    public void setBatch(String batch) {
        this.batch = batch;
    }
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getCost() {
        return this.cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public String getStat() {
        return this.stat;
    }
    
    public void setStat(String stat) {
        this.stat = stat;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


